### ISSUE TITLE
Plugin archibp appears to cause issues with datainjection plugin

### ISSUE THREAD

**Issue by derry43** [ericferon/glpi-archibp#1]
GLPI version: 9.5.7
archibp version: 1.0.1
datainjection version: 2.9.0

After installing the **archibp** plugin 1.0.1 in GLPI 9.5.7 with the plugin is datainjection 2.9.0 also installed, this prevents myself (and others) from creating a datainjection mode as the Save button does not display. Disabling the archibp plugin fixes this issue. 

Upon checking the log files, I find the following error:

```
*** Uncaught Exception Error: Class 'PluginArchibpTaskInjection' not found in C:\inetpub\wwwroot\glpi\plugins\datainjection\inc\injectiontype.class.php at line
```
Which seems to stem from the line ...

```
archibp/hook.php:   $INJECTABLE_TYPES['PluginArchibpTaskInjection'] = 'datainjection';
```

Archibp does not appear to define the **PluginArchibpTaskInjection** class, unlike the **archisw** plugin, which defines the similar purpose class, **PluginArchiswSwcomponentInjection**, in its own class file.

```
archisw/hook.php:   $INJECTABLE_TYPES['PluginArchiswSwcomponentInjection'] = 'datainjection';
archisw/inc/swcomponentinjection.class.php: * Class PluginArchiswSwcomponentInjection
archisw/inc/swcomponentinjection.class.php:class PluginArchiswSwcomponentInjection extends PluginArchiswSwcomponent
```

**Comment by ericferon** [comment]
Fixed with v1.0.4.
K.r,
