### ISSUE TITLE
Does not want to install on version GLPI 10.0.0

### ISSUE THREAD

**Issue by v0vik** [ericferon/glpi-archibp#2]
![screen_2022-06-23_11-43-32](https://user-images.githubusercontent.com/18086755/175269698-a61c9a6f-624e-4ffd-961b-e08ed49f3327.png)

Does not want to install on version GLPI 10.0.0
When I click Enable I get this:
![screen2_2022-06-23_11-45-40](https://user-images.githubusercontent.com/18086755/175270431-108c66fa-d27d-4b2f-ab3e-b34354f3973a.png)

**Comment by ericferon** [comment]
Hi,
The message is misleading : it should be read "The plugin 'archisw' (a.k.a Apps Structure) must be installed before using 'archibp' (Business Process).
I will fix the message in v1.0.5.
K.r,
