### ISSUE TITLE
Unable to add a new Business Proces

### ISSUE THREAD

**Issue by dramaker** [ericferon/glpi-archibp#5]
Plugin was installed/activated without issues.
However, when clicking the 'Add' button, the page doesn't load.

In the logging, when clicking the 'Add' button, below entry is created many times:

----------
[2024-04-12 15:34:43] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "plugin_dataflows_configdfhaligns_id" in C:\inetpub\wwwroot\glpi\plugins\archibp\inc\task.class.php at line 524
  Backtrace :
  plugins\archibp\inc\task.class.php:438             PluginArchibpTask->displayField()
  src\CommonGLPI.php:680                             PluginArchibpTask->showForm()
  ajax\common.tabs.php:120                           CommonGLPI::displayStandardTab()
----------

I'm running GLPI v10.0.12 with plugins Dataflows v3.0.9, Business Process v2.0.8, App Structure v3.0.18 & Statecheck Rules v2.4.3.

If anyone could investigate or advise, it would be appreciated.

**Comment by ericferon** [comment]
Hi,
Indeed, there is a bug.
Fixed with v2.0.9.
K.r,

**Comment by dramaker** [comment]
Thanks a lot, it works now.
