### ISSUE TITLE
Activate/ Deactivate/ Uninstall

### ISSUE THREAD

**Issue by ajaysajay** [ericferon/glpi-archibp#7]
After GLPI upgrade from 10.0.11 to 10.0.17, plugin was deactivated. 
I was not alble to assign tickets to Business Processes, so I tried deactivating and uninstalling plugin and then installing again (from https://<<my_glpi_portal>>.com/front/marketplace.php. At this stage it seems messed up:
* If I activate archibp, entire glpi portal goes blank.
* If I deactivate archibp from glpi console, portal works.
* If I activate via console, and then go to configure plugin, I see this message on Plugin Config Page:

Table 'glpi2024.glpi_plugin_archibp_configbps' doesn't exist

Also tried to delete plugin from portal - no response. I then tried to delete plugin from console and saw this error:

 Processing plugin "archibp"...
SQL Error "1146": Table 'glpiXXXX.glpi_plugin_archibp_configbplinks' doesn't exist in query "SELECT `name` FROM `glpi_plugin_archibp_configbplinks` WHERE `name` LIKE 'PluginArchibp%' AND (`as_view_on` IS NULL OR `as_view_on` = '')"
Uncaught Exception Error: Call to a member function fetch_assoc() on bool in /var/www/glpiXXXX/glpi/src/DBmysql.php at line 613

It's a running instance of GLPI, so I'm cluless how to bring plugin back to a clean state.

**Comment by ericferon** [comment]
Hi,
It's difficult to assess the state of archibp, after your different trials.
If you can access the glpi db, you can try to create the glpi_plugin_archibp_configbps table : execute the sql statements contained in lines 261 to 335 of file inc/empty-2.0.1.sql.
If this process fails to make archibp running again, you can suppress the directory marketplace/archibp and download archibp again.
K.r,

**Comment by ajaysajay** [comment]
I understant that the state of archibp is not good after sequence of trials.
The inputs provided by you will be helpful. Thank you for the direction. 
I'll recreate the table as suggested based on line suggested sql and share results.

**Comment by ajaysajay** [comment]
Created glpi_plugin_archibp_configbps table and encountered few more error messages. Accordingly, created following tables and reference data based on `empty-2.0.1.sql`. 
**Tables:**
- glpi_plugin_archibp_configbps
- glpi_plugin_archibp_fieldgroups
- glpi_plugin_archibp_configbpdatatypes
- glpi_plugin_archibp_configbplinks
- glpi_plugin_archibp_configbpdbfieldtypes
- glpi_plugin_archibp_tasktargets
- glpi_plugin_archibp_taskstates
- glpi_plugin_archibp_configbphaligns

**Reference Data:**
- glpi_displaypreferences data 
- Statecheck rules data
- glpi_plugin_archibp_configbphaligns data
- glpi_plugin_archibp_configbpdbfieldtypes data

Now everyting seems working fine. Thank you!
