### ISSUE TITLE
Tickets - Add Items - Business Process

### ISSUE THREAD

**Issue by ajaysajay** [ericferon/glpi-archibp#8]
GLPI 10.0.17 | Ubuntu 22.04.5 LTS | Current language : en_US

Installed and activated both glpi-archisw and glpi-archibp. Additional information:
1. `Setup > General > Impact Analysis > Enabled itemtypes >` Includes Business Processes
2. `Setup > Dropdowns > Business Processes > ` Defined Criticity, Targets and Status. Rest of the standard configuration.
3. `Profiles > Business Processes Tab >` All Indicators Active under General and HelpDesk (including Associable items to a ticket) sections.
4. Can see `Business Processes` Tab on `Groups` Page as well as `Profile` Page
5. Able to see `Apps Structures` Tab in `Entity` Page, but cannot see `Business Process` Tab on `Entity` Page - not sure if it expected plugin behavior 

Issues:
1. `Profiles > Assistance Tab > Association > Associable items to tickets, changes and problems > ` Can see and Assign Apps Structures, but cannot see and assign Business Process.
2. In Ticket update, I can see `Apps Structures` and add an Apps Structures Item, but cannot see `Business Processes` in `Component Search` and cannot select a Business Process Item.

Had issues with deactivation/ activation of plugin, which were resolved by recreating missing table/ data. Not sure if still some configuration is missing, or Business Processes cannot be linked to a Ticket. Any help / guidance is appreciated.

**Comment by ajaysajay** [comment]
Also saw the following error message on https://<portal>/archibp/front/swcomponent.php page:

`Unknown column 'glpi_plugin_archibp_swcomponents.completename' in 'field list'`

Updated glpi_plugin_archibp_swcomponents view to add `glpi_plugin_archisw_swcomponents`.`completename` AS `completename` and now this is gone. Left existing `glpi_plugin_archisw_swcomponents.completename as name` untouched.

Also recreated all plugin tables / data based on empty-2.0.1.sql. Not sure what is missing!

But I still do not see `Business Processes` in Add Items to Ticket options.

**Comment by ajaysajay** [comment]
Disabled/ Uninstalled and cleaned all traces from `marketplace` and `plugin` folders. Dropped archibp related tables. Reinstalled and activated from a clean state. 
Still cannot see `Business Process` in `Profiles > Assistance Tab > Association > Associable items to tickets`.

**Comment by ericferon** [comment]
Hi,
The link with tickets was not really implemented in the past, but I have added it in v2.0.12.
K.r,
